### ISSUE TITLE
can you provide the html and js code?

### ISSUE THREAD

**Issue by willxiang** [m-hassan-tariq/SFTPFileUploadUsingWebAPIandAngularJS#1]
I see your project but not have the html and js code.
can you upload html and js code to github?
thx!

**Comment by iamtchelo** [comment]
@willxiang you can see here:

html => https://github.com/m-hassan-tariq/SFTPFileUploadUsingWebAPIandAngularJS/blob/master/SftpUploadAngularJS/Views/Home/Index.cshtml

js => https://github.com/m-hassan-tariq/SFTPFileUploadUsingWebAPIandAngularJS/tree/master/SftpUploadAngularJS/Scripts

**Comment by willxiang** [comment]
@marcelodeveloper  
Oh...I am careless ,Thank you!!!

**Comment by m-hassan-tariq** [comment]
Thanks @marcelodeveloper for the quick response.

**Comment by m-hassan-tariq** [comment]
@willxiang 
You may also checkout below link for assistance.

https://hassantariqblog.wordpress.com/2015/04/25/sftp-file-upload-using-asp-net-web-api-and-angularjs/

**Comment by willxiang** [comment]
@m-hassan-tariq 
Yes I've read it and that article helpful to me ! Thank you!

**Comment by iamtchelo** [comment]
@m-hassan-tariq :p
